### ISSUE TITLE
Movie's detail not updated when using the scroll wheel 

### ISSUE THREAD

**Issue by ducarroz** [montagejs/popcorn#20]
When you "scroll" through movies using the mouse's wheel, the movie detail section does not correspond to the movie currently displayed at the center of the flow but to the last movie you have clicked on.

This issue occurs on Chrome Dev Version 36.0.1933.0 dev on Mac OS X 10.9.2

**Comment by hthetiot** [comment]
Should be fixed already.

**Comment by jonfu86** [comment]
Confirmed fixed.
